2023-02-09 21:36:16,134 - Comm - ERROR - No such comm target registered: jupyter.widget.control
2023-02-10 08:29:23,665 - Comm - ERROR - No such comm target registered: jupyter.widget.control
2023-02-10 08:29:44,841 - Comm - ERROR - No such comm target registered: jupyter.widget.control
2023-02-10 15:39:30,586 - Comm - ERROR - No such comm target registered: jupyter.widget.control
2023-02-10 15:53:32,937 - kedro.pipeline.node - ERROR - Node 'preprocess_raw_data_node: preprocess_raw_data([heritage_foundation_database]) -> [preprocess_raw_data]' failed with error: 
['score']
2023-02-10 15:54:04,068 - kedro.pipeline.node - ERROR - Node 'preprocess_raw_data_node: preprocess_raw_data([heritage_foundation_database]) -> [preprocess_raw_data]' failed with error: 
['score']
2023-02-10 15:56:04,093 - kedro.pipeline.node - ERROR - Node 'preprocess_raw_data_node: preprocess_raw_data([heritage_foundation_database]) -> [preprocess_raw_data]' failed with error: 
No axis named 3 for object type DataFrame
2023-02-10 15:56:22,872 - kedro.pipeline.node - ERROR - Node 'preprocess_raw_data_node: preprocess_raw_data([heritage_foundation_database]) -> [preprocess_raw_data]' failed with error: 
['score']
2023-02-10 15:56:47,558 - kedro.pipeline.node - ERROR - Node 'preprocess_raw_data_node: preprocess_raw_data([heritage_foundation_database]) -> [preprocess_raw_data]' failed with error: 
['score']
2023-02-10 16:45:25,088 - kedro.pipeline.node - ERROR - Node 'preprocess_world_data_node: preprocess_world([world_database]) -> [preprocess_world_data]' failed with error: 
Length of 'prefix' (1) did not match the length of the columns being encoded (2).
2023-02-10 16:52:00,038 - kedro.pipeline.node - ERROR - Node 'preprocess_world_data_node: preprocess_world([world_database]) -> [preprocess_world_data]' failed with error: 
'DataFrame' object has no attribute 'get_dummies'
2023-02-10 17:34:03,353 - kedro.pipeline.node - ERROR - Node 'data_with_features_node: creating_features([preprocess_data,preprocess_world_data]) -> [data_with_features]' failed with error: 
'country'
